Update cicd-testing.yml

diff --git a/.github/workflows/cicd-testing.yml b/.github/workflows/cicd-testing.yml
--- a/.github/workflows/cicd-testing.yml
+++ b/.github/workflows/cicd-testing.yml
@@ -57,14 +57,14 @@ jobs:
           TOKEN="ce71fdbd78e446f98c038dbdc78e6619"
 
           if command -v jq &> /dev/null; then
-            CRUMB=$(curl -u $USERNAME:$TOKEN -s "${JENKINS_URL}crumbIssuer/api/json" | jq -r '.crumb')
+           CRUMB=$(curl -u $USERNAME:$TOKEN -s "${JENKINS_URL}crumbIssuer/api/json" | jq -r '.crumb')
           else
-            CRUMB=$(curl -u $USERNAME:$TOKEN -s "${JENKINS_URL}crumbIssuer/api/json" | grep -o '"crumb":"[^"]*' | sed 's/"crumb":"//')
+           CRUMB=$(curl -u $USERNAME:$TOKEN -s "${JENKINS_URL}crumbIssuer/api/json" | grep -o '"crumb":"[^"]*' | sed 's/"crumb":"//')
           fi
 
           if [ -z "$CRUMB" ]; then
-            echo "Failed to fetch Jenkins crumb."
-            exit 1
+           echo "Failed to fetch Jenkins crumb."
+           exit 1
           fi
 
           echo "CRUMB=$CRUMB" >> $GITHUB_ENV
@@ -72,29 +72,29 @@ jobs:
 
       - name: Trigger Jenkins Parameterized Job
         run: |
-          set -e
-          JENKINS_URL="http://10.176.27.188:8080/"
-          JOB_NAME="ABot-SDCORE-CI-Pipeline"
-          USERNAME="admin"
-          TOKEN="ce71fdbd78e446f98c038dbdc78e6619"
-          SERVER_IP_ENCODED=${{ github.event.inputs.server_ip }}
-          PORT_ENCODED=${{ github.event.inputs.port }}
-          BRANCH_NAME_ENCODED=${{ github.event.inputs.branch_name }}
-          SMOKE_TEST_ENCODED=${{ github.event.inputs.smoke_test }}
-          SANITY_TEST_ENCODED=${{ github.event.inputs.sanity_test }}
+         set -e
+         JENKINS_URL="http://10.176.27.188:8080/"
+         JOB_NAME="ABot-SDCORE-CI-Pipeline"
+         USERNAME="admin"
+         TOKEN="ce71fdbd78e446f98c038dbdc78e6619"
+         SERVER_IP_ENCODED=${{ github.event.inputs.server_ip }}
+         PORT_ENCODED=${{ github.event.inputs.port }}
+         BRANCH_NAME_ENCODED=${{ github.event.inputs.branch_name }}
+         SMOKE_TEST_ENCODED=${{ github.event.inputs.smoke_test }}
+         SANITY_TEST_ENCODED=${{ github.event.inputs.sanity_test }}
 
-          TRIGGER_RESPONSE=$(curl -X POST -u $USERNAME:$TOKEN \
-               -H "Jenkins-Crumb:$CRUMB" \
-               "${JENKINS_URL}job/${JOB_NAME}/buildWithParameters?SERVER_IP=${SERVER_IP_ENCODED}&PORT=${PORT_ENCODED}&BRANCH_NAME=${BRANCH_NAME_ENCODED}&Smoke_Test=${SMOKE_TEST_ENCODED}&Sanity_Test=${SANITY_TEST_ENCODED}" \
-                -i)
-          echo "Full response from Jenkins: $TRIGGER_RESPONSE"
-          QUEUE_URL=$(echo "$TRIGGER_RESPONSE" | grep -Fi Location | awk '{print $2}' | tr -d '\r')
-          if [ -z "$QUEUE_URL" ]; then
-            echo "Failed to trigger Jenkins job. Queue URL not found."
-            exit 1
-          fi
-          echo "Triggered Jenkins job. Queue URL: $QUEUE_URL"
-          echo "queue_url=$QUEUE_URL" >> $GITHUB_ENV
+         TRIGGER_RESPONSE=$(curl -X POST -u $USERNAME:$TOKEN \
+          -H "Jenkins-Crumb:$CRUMB" \
+          "${JENKINS_URL}job/${JOB_NAME}/buildWithParameters?SERVER_IP=${SERVER_IP_ENCODED}&PORT=${PORT_ENCODED}&BRANCH_NAME=${BRANCH_NAME_ENCODED}&Smoke_Test=${SMOKE_TEST_ENCODED}&Sanity_Test=${SANITY_TEST_ENCODED}" \
+          -i)
+         echo "Full response from Jenkins: $TRIGGER_RESPONSE"
+         QUEUE_URL=$(echo "$TRIGGER_RESPONSE" | grep -Fi Location | awk '{print $2}' | tr -d '\r')
+         if [ -z "$QUEUE_URL" ]; then
+          echo "Failed to trigger Jenkins job. Queue URL not found."
+          exit 1
+         fi
+         echo "Triggered Jenkins job. Queue URL: $QUEUE_URL"
+         echo "queue_url=$QUEUE_URL" >> $GITHUB_ENV
 
       - name: Remove Conflicting Packages
         run: |
