Update cicd-testing.yml

diff --git a/.github/workflows/cicd-testing.yml b/.github/workflows/cicd-testing.yml
--- a/.github/workflows/cicd-testing.yml
+++ b/.github/workflows/cicd-testing.yml
@@ -24,37 +24,38 @@ jobs:
       - name: Checkout Code
         uses: actions/checkout@v2
 
-      - name: Trigger Jenkins Parameterized Job
-        run: |
-          set -e
-          JENKINS_URL="http://10.176.27.188:8080/"
-          JOB_NAME="ABot-SDCORE-CI-Pipeline"
-          USERNAME="admin"
-          TOKEN="ce71fdbd78e446f98c038dbdc78e6619"
-
-      - name: Set Up Variables & trigger the job
+      - name: Set Up Variables 
         run: |
           echo "SERVER_IP=${{ github.event.inputs.server_ip }}" >> $GITHUB_ENV
           echo "BRANCH_NAME=${{ github.event.inputs.branch_name }}" >> $GITHUB_ENV
-          echo "PORT="${{ github.event.inputs.port }}" >> $GITHUB_ENV
-           # URL encode parameters
-          SERVER_IP_ENCODED=$(echo $SERVER_IP | jq -s -R -r @uri)
-          PORT_ENCODED=$(echo $PORT | jq -s -R -r @uri)
-          BRANCH_NAME_ENCODED=$(echo $BRANCH_NAME | jq -s -R -r @uri)
 
-          # Trigger the Jenkins parameterized job with inputs
-          TRIGGER_RESPONSE=$(curl -X POST -u $USERNAME:$TOKEN "$JENKINS_URL/job/$JOB_NAME/buildWithParameters?SERVER_IP=$SERVER_IP_ENCODED&PORT=$PORT_ENCODED&BRANCH_NAME=$BRANCH_NAME_ENCODED" -i)
+      - name: Trigger Jenkins Parameterized Job
+        run: |
+         set -e
+         JENKINS_URL="http://10.176.27.188:8080/"
+         JOB_NAME="ABot-SDCORE-CI-Pipeline"
+         USERNAME="admin"
+         TOKEN="${{ secrets.JENKINS_TOKEN }}"
+
+         SERVER_IP_ENCODED=$(echo ${{ github.event.inputs.server_ip }} | jq -s -R -r @uri)
+         PORT_ENCODED=$(echo ${{ github.event.inputs.port }} | jq -s -R -r @uri)
+         BRANCH_NAME_ENCODED=$(echo ${{ github.event.inputs.branch_name }} | jq -s -R -r @uri)
+
+         TRIGGER_RESPONSE=$(curl -X POST -u $USERNAME:$TOKEN \
+          "${JENKINS_URL}job/${JOB_NAME}/buildWithParameters?SERVER_IP=${SERVER_IP_ENCODED}&PORT=${PORT_ENCODED}&BRANCH_NAME=${BRANCH_NAME_ENCODED}" \
+          -D - -o /dev/null)
+
+         QUEUE_URL=$(echo "$TRIGGER_RESPONSE" | grep -Fi Location | awk '{print $2}' | tr -d '\r')
+
+         if [ -z "$QUEUE_URL" ]; then
+          echo "Failed to trigger Jenkins job. Queue URL not found."
+          exit 1
+         fi
+
+         echo "Triggered Jenkins job. Queue URL: $QUEUE_URL"
+         echo "queue_url=$QUEUE_URL" >> $GITHUB_ENV
+
           
-          # Extract the queue URL from the trigger response to track the build
-          QUEUE_URL=$(echo "$TRIGGER_RESPONSE" | grep -Fi Location | awk '{print $2}' | tr -d '\r')
-
-          if [ -z "$QUEUE_URL" ]; then
-            echo "Failed to trigger Jenkins job. Queue URL not found."
-            exit 1
-          fi
-
-          echo "Triggered Jenkins job. Queue URL: $QUEUE_URL"
-          echo "queue_url=$QUEUE_URL" >> $GITHUB_ENV
           
       - name: Remove Conflicting Packages
         run: |
